rvm:
  - 1.8.7
  - 1.9.2
  - ree
  - ruby-head
  - rbx
  - rbx-2.0
  - jruby
env:
  # Don't get any ideas, this will only work with Klarna's test-server. ;)
  - KLARNA_ESTORE=1562,V6Y95XQ46ymmAWA
notifications:
  disabled: true